//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.11 at 02:41:16 PM GMT-03:00 
//


package main.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the main.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: main.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RetificarLoteComunicacaoResponse }
     * 
     */
    public RetificarLoteComunicacaoResponse createRetificarLoteComunicacaoResponse() {
        return new RetificarLoteComunicacaoResponse();
    }

    /**
     * Create an instance of {@link RecebeArquivo }
     * 
     */
    public RecebeArquivo createRecebeArquivo() {
        return new RecebeArquivo();
    }

    /**
     * Create an instance of {@link ValidarAssinaturaLoteResponse }
     * 
     */
    public ValidarAssinaturaLoteResponse createValidarAssinaturaLoteResponse() {
        return new ValidarAssinaturaLoteResponse();
    }

    /**
     * Create an instance of {@link ReciboLoteComunicacaoResponse }
     * 
     */
    public ReciboLoteComunicacaoResponse createReciboLoteComunicacaoResponse() {
        return new ReciboLoteComunicacaoResponse();
    }

    /**
     * Create an instance of {@link RecebeArquivoResponse }
     * 
     */
    public RecebeArquivoResponse createRecebeArquivoResponse() {
        return new RecebeArquivoResponse();
    }

    /**
     * Create an instance of {@link VerificarComunicacao }
     * 
     */
    public VerificarComunicacao createVerificarComunicacao() {
        return new VerificarComunicacao();
    }

    /**
     * Create an instance of {@link ValidarAssinaturaLote }
     * 
     */
    public ValidarAssinaturaLote createValidarAssinaturaLote() {
        return new ValidarAssinaturaLote();
    }

    /**
     * Create an instance of {@link VerificarComunicacaoResponse }
     * 
     */
    public VerificarComunicacaoResponse createVerificarComunicacaoResponse() {
        return new VerificarComunicacaoResponse();
    }

    /**
     * Create an instance of {@link ReciboLoteComunicacao }
     * 
     */
    public ReciboLoteComunicacao createReciboLoteComunicacao() {
        return new ReciboLoteComunicacao();
    }

    /**
     * Create an instance of {@link RetificarLoteComunicacao }
     * 
     */
    public RetificarLoteComunicacao createRetificarLoteComunicacao() {
        return new RetificarLoteComunicacao();
    }

    /**
     * Create an instance of {@link CancelarLoteComunicacao }
     * 
     */
    public CancelarLoteComunicacao createCancelarLoteComunicacao() {
        return new CancelarLoteComunicacao();
    }

    /**
     * Create an instance of {@link EnviarLoteComunicacaoResponse }
     * 
     */
    public EnviarLoteComunicacaoResponse createEnviarLoteComunicacaoResponse() {
        return new EnviarLoteComunicacaoResponse();
    }

    /**
     * Create an instance of {@link CancelarLoteComunicacaoResponse }
     * 
     */
    public CancelarLoteComunicacaoResponse createCancelarLoteComunicacaoResponse() {
        return new CancelarLoteComunicacaoResponse();
    }

    /**
     * Create an instance of {@link EnviarLoteComunicacao }
     * 
     */
    public EnviarLoteComunicacao createEnviarLoteComunicacao() {
        return new EnviarLoteComunicacao();
    }

}
