//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.11 at 02:41:16 PM GMT-03:00 
//


package main.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="arquivoData" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="npedido" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "arquivoData",
    "npedido"
})
@XmlRootElement(name = "RecebeArquivo")
public class RecebeArquivo {

    protected byte[] arquivoData;
    protected String npedido;

    /**
     * Gets the value of the arquivoData property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getArquivoData() {
        return arquivoData;
    }

    /**
     * Sets the value of the arquivoData property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setArquivoData(byte[] value) {
        this.arquivoData = ((byte[]) value);
    }

    /**
     * Gets the value of the npedido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNpedido() {
        return npedido;
    }

    /**
     * Sets the value of the npedido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNpedido(String value) {
        this.npedido = value;
    }

}
