//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.11 at 02:41:16 PM GMT-03:00 
//


package main.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReciboLoteComunicacaoResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reciboLoteComunicacaoResult"
})
@XmlRootElement(name = "ReciboLoteComunicacaoResponse")
public class ReciboLoteComunicacaoResponse {

    @XmlElement(name = "ReciboLoteComunicacaoResult")
    protected String reciboLoteComunicacaoResult;

    /**
     * Gets the value of the reciboLoteComunicacaoResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReciboLoteComunicacaoResult() {
        return reciboLoteComunicacaoResult;
    }

    /**
     * Sets the value of the reciboLoteComunicacaoResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReciboLoteComunicacaoResult(String value) {
        this.reciboLoteComunicacaoResult = value;
    }

}
